version: 2.1
orbs:
 aws-cli: circleci/aws-cli@1.3.2
jobs:
  static-code-pipline:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Setup Stage
          command: |
             if [ $CIRCLE_BRANCH == "dev" ]
             then
               STAGE=dev;
               ROLE_ARN=$DEV_AWS_STS_ROLE_ARN;
             elif [ $CIRCLE_BRANCH == "qa" ]
             then
               STAGE=qa;
             elif [ $CIRCLE_BRANCH == "main" ] || [ $CIRCLE_BRANCH == "master" ]
             then
               STAGE=prod;
               ROLE_ARN=$PROD_AWS_STS_ROLE_ARN;
             else
               echo "Undefined stage"
             fi

             CREDENTIALS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name build-$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM | jq '.Credentials')

             export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.AccessKeyId')

             export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.SecretAccessKey')

             export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.SessionToken')

             aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default

             aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default

             aws configure set aws_session_token $AWS_SESSION_TOKEN --profile default
             
             aws s3  sync ./a/ s3://$STAGE-staticu/img --delete --profile default

workflows:
  aws-cli:
    jobs:
      - static-code-pipline:
          context: aws
          filters:
            branches:
              only:
                - dev
                - qa
                - main
                - master
                - v2
