version: '2.1'
orbs:
  aws-cli: underw8/aws-assume-role@0.1.0
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/assume:
          profile-name: default
      - run:
          command: |
            aws s3 ls --profile default
          name: Test the assumed role
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws