version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  configure-role-arn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - aws-cli/role-arn-setup:
          profile-name: new-profile
          role-arn: $DEV_AWS_STS_ROLE_ARN
          source-profile: default
      - run: >-
          aws sts assume-role --role-arn  $DEV_AWS_STS_ROLE_ARN --role-session-name AWSCLI-Session;
          aws s3 ls  --profile default
workflows:
  aws-cli:
    jobs:
      - configure-role-arn:
          context: aws
          filters:
            branches:
              only:
                - dev
                - qa
                - main
                - master
                - v2