version: 2.1
orbs:
  aws-cli: underw8/aws-assume-role@0.1.0
jobs:
  static-code-pipline:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/assume:
          profile-name: default
      - run:
          name: Setup Stage
          command: |
            if [ $CIRCLE_BRANCH == "dev" ]
            then
              echo 'export STAGE=dev' >> ~/.bashrc
            elif [ $CIRCLE_BRANCH == "qa" ]
            then
              echo 'export STAGE=qa' >> ~/.bashrc
            elif [ $CIRCLE_BRANCH == "main" ] || [ $CIRCLE_BRANCH == "master" ]
            then
              echo 'export STAGE=prod' >> ~/.bashrc
            else
              echo "Undefined stage"
            fi
            echo 'export CI=false' >> ~/.bashrc
      - run:
          name: Copy Dist Files to AWS S3 Buckets
          command: |
            source ~/.bashrc;
            aws s3 ls --profile default;

workflows:
  aws-cli:
    jobs:
      - static-code-pipline:
          context: aws
          filters:
            branches:
              only:
                - dev
                - qa
                - main
                - master
                - v2
