version: 2.1
orbs:
 aws-cli: circleci/aws-cli@1.3.2
jobs:
  static-code-pipline:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Setup Stage
          command: |
             ROLE_ARN=$DEV_AWS_STS_ROLE_ARN;

workflows:
  aws-cli:
    jobs:
      - static-code-pipline:
          context: aws
          filters:
            branches:
              only:
                - dev
                - qa
                - main
                - master
                - v2